Importing Libraries

In [8]:
import numpy as np
import pandas as pd

In [9]:
time = pd.read_csv('/content/messages.csv')

In [10]:
date = pd.read_csv('/content/orders.csv')

Extract Date

In [13]:
date.head(4)

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1

In [18]:
date.drop(columns=['product_id','city_id','orders'],inplace=True)

In [19]:
date['date'] = pd.to_datetime(date['date'])

In [20]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 7.9 KB

In [21]:
date.head(4)

        date
0 2019-12-10
1 2018-08-15
2 2018-10-23
3 2019-08-17

In [22]:
date['date_year'] = date['date'].dt.year

In [28]:
date['date_month'] = date['date'].dt.month_name()

In [29]:
date['date_day'] = date['date'].dt.day_name()

In [74]:
date['date_week'] = date['date'].dt.week

<ipython-input-74-959878224f78>:1: FutureWarning: Series.dt.weekofyear and Series.dt.week have been deprecated. Please use Series.dt.isocalendar().week instead.
  date['date_week'] = date['date'].dt.week

In [77]:
date['date_quater'] = date['date'].dt.quarter

In [95]:
date['date_semester'] = np.where(date['date_quater'].isin([1,2]),1,2)

In [96]:
date.sample(4)

,date,date_year,date_month,date_day,date_week,date_quater,date_semester
543,2019-12-05,2019,December,Thursday,49,4,2
544,2018-08-01,2018,August,Wednesday,31,3,2
572,2019-07-03,2019,July,Wednesday,27,3,2
193,2019-05-18,2019,May,Saturday,20,2,1

In [58]:
import datetime

In [59]:
today = datetime.datetime.today()

In [60]:
today

datetime.datetime(2023, 4, 4, 8, 38, 32, 401377)

In [73]:
(((today - date['date']).dt.days)/365)*12

0      39.813699
1      55.660274
2      53.391781
3      43.594521
4      50.926027
         ...
995    53.884932
996    51.945205
997    46.947945
998    49.084932
999    41.654795
Name: date, Length: 1000, dtype: float64

Extract Time

In [98]:
time.head(4)

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...

In [99]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [101]:
time['date'] = pd.to_datetime(time['date'])

In [102]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [103]:
time.head()

                 date                                                msg
0 2013-12-15 00:50:00                           ищу на сегодня мужика 37
1 2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2 2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3 2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4 2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [105]:
time['time_hour'] = time['date'].dt.hour

In [107]:
time['time_minute'] = time['date'].dt.minute

In [108]:
time['time_second'] = time['date'].dt.second

In [116]:
time.sample(7)

,date,msg,time_hour,time_minute,time_second
649,2013-02-22 23:18:00,Ж ищет серъезного М для с/с,23,18,0
183,2013-10-01 01:43:00,Укротители есть? а то я распоясалась жду номерок),1,43,0
238,2016-12-23 23:22:00,М 48 вменяем..ищит нежную Жен для и/о.050 6959...,23,22,0
635,2012-09-12 01:12:00,ИЩУ ДАМУ ДО 50 С/ПАРУ ДЛЯ ВЗРОСЛЫХ ВСТРЕЧ.067 ...,1,12,0
599,2013-02-26 23:50:00,Янка привет тебе по Жовтневке думаю ты скоро б...,23,50,0
856,2015-01-31 01:24:00,М 41.185.75. Ищю Женщ.для Всего. 0639642652,1,24,0
610,2014-12-28 00:58:00,есть не скромная девушка? 063 2 431 431,0,58,0

In [135]:
(today - time['date'])/np.timedelta64(1,'m')

0      4.892149e+06
1      4.696379e+06
2      5.396178e+06
3      4.391048e+06
4      4.962808e+06
           ...
995    5.812309e+06
996    4.834645e+06
997    5.504222e+06
998    5.671265e+06
999    4.622954e+06
Name: date, Length: 1000, dtype: float64